spring.application.name=roommates_BE

jwt.secret=R8vK3mQ7xN2pL9sW4dF6hJ1cZ5tY0bG8uE3rA7kP2mX6qV9n

spring.datasource.url=jdbc:mysql://localhost:3306/roommates_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080